CREATE PROCEDURE VALIDATE_USER @EMAILID NVARCHAR(256)
As
SELECT 1 FROM USERS WHERE EMAILID=@EMAILID
GO


exec VALIDATE_USER "richa.goya90@gmail.com"

DROP PROCEDURE VALIDATE_USER

CREATE PROCEDURE LOGIN_USER @USERNAME NVARCHAR(256),@PASSWORD NVARCHAR(256)
As
SELECT FIRSTNAME,LASTNAME,EMAILID,PHONENUMBER FROM USERS WHERE USERNAME=@USERNAME AND @PASSWORD=PASSWORD
GO

EXEC LOGIN_USER "richa.goyal90","richa"