select * from Users;
create table APPOINTMENT_DETAILS
(
APPOINTMENT_ID INT PRIMARY KEY IDENTITY,
HOST_USERID INT NOT NULL,
GUEST_USERID INT NOT NULL,
APP_SUBJECT VARCHAR(256) NOT NULL,
DATENTIME DATETIME NOT NULL,
STATUS VARCHAR(256) NOT NULL)

dROP TABLE APPOINTMENT_DETAILS

Drop Procedure CurrentDateAppointment


CREATE PROCEDURE CurrentDateAppointment @USER_ID INT
AS
SELECT APPOINTMENT_ID,(SELECT FIRSTNAME FROM USERS WHERE UserId=HOST_USERID),(SELECT FIRSTNAME FROM USERS WHERE USERID=GUEST_USERID),DATENTIME,APP_SUBJECT 
FROM APPOINTMENT_DETAILS 
WHERE DATENTIME BETWEEN CONVERT(DATE,GETDATE()) AND DATEADD(DAY,1,CONVERT(DATE,GETDATE()))
AND (HOST_USERID=@USER_ID OR GUEST_USERID=@USER_ID)
GO

CREATE PROCEDURE USERLIST 
AS 
SELECT CONCAT(FIRSTNAME,',',LASTNAME) FROM USERS;
GO
